#include "ai_model.h"
#include "feature_params.h"  // ai_model/feature_params.h — auto-generated from the quantizer JSONs
#include "ui/screens.h"
#include "ui/eco_tree_images.h"  // generated by assets/tree/gen_assets.py

#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

// ---- Model selection -------------------------------------------------------
// Exactly one trained model is compiled in. Switch the active model by changing
// AI_MODEL_VARIANT (here or via a -D build flag). Only the selected model header
// is #included, so the unused model's tree arrays never reach the compiler.
//   AI_MODEL_VARIANT_RANDOM_FOREST -> ai_model/driving_style_model.h (current)
//   AI_MODEL_VARIANT_EXTRA_TREES   -> ai_model/eco_model.h           (legacy)
// Both models share the same 20 features and feature order; only the trained
// tree and the MinMaxScaler params (feature_params.h) differ.
#define AI_MODEL_VARIANT_EXTRA_TREES    0
#define AI_MODEL_VARIANT_RANDOM_FOREST  1

#ifndef AI_MODEL_VARIANT
#define AI_MODEL_VARIANT  AI_MODEL_VARIANT_EXTRA_TREES
#endif

#if AI_MODEL_VARIANT == AI_MODEL_VARIANT_RANDOM_FOREST
    #include "driving_style_model.h"
    #define AI_MODEL_PREDICT  driving_style_model_predict
    #define AI_FEAT_SCALE     RANDOM_FOREST_FEAT_SCALE
    #define AI_FEAT_MIN       RANDOM_FOREST_FEAT_MIN
#elif AI_MODEL_VARIANT == AI_MODEL_VARIANT_EXTRA_TREES
    #include "eco_model.h"
    #define AI_MODEL_PREDICT  eco_model_predict
    #define AI_FEAT_SCALE     EXTRA_TREES_FEAT_SCALE
    #define AI_FEAT_MIN       EXTRA_TREES_FEAT_MIN
#else
    #error "Invalid AI_MODEL_VARIANT — pick AI_MODEL_VARIANT_EXTRA_TREES or AI_MODEL_VARIANT_RANDOM_FOREST"
#endif
// ---------------------------------------------------------------------------

// Window length must match WIN_N from the ML notebooks: 5s at 10Hz = 50 samples.
// The logger task feeds one sample every 100ms (see sd_card.c), matching the
// notebook's fixed 10Hz resample grid.
#define WIN_SIZE  50
#define DIFF_SIZE 49  // WIN_SIZE - 1

// Fixed sample period (s) used for per-second derivatives, matching the notebook
// constant DT = 0.1 (d_throttle_s, d_brake_s, jerk_ms3 are all divided by DT).
#define DT_S 0.1f

#define AI_SCORE_MIN   0
#define AI_SCORE_MAX   1000
#define AI_SCORE_START 500
// Loss aversion: the score drops faster than it climbs, so aggressive driving is
// "felt" more strongly than eco driving is rewarded. Tunable.
#define AI_SCORE_ECO_STEP 2
#define AI_SCORE_AGGRESSIVE_STEP  4

// Eco-tree gamification: score (and sustained aggression) -> growth stage.
//   stage 0      = withered seed (sustained aggressive driving)
//   stages 1..6  = seed -> seedling -> sapling -> mature -> flowering -> fruiting
#define AI_TREE_GROWTH_STAGES   6
// Consecutive AGGRESSIVE windows before the seed withers (10Hz feed -> ~10s).
#define AI_TREE_WITHER_WINDOWS  100
// Score the driver must climb back to (via eco driving) for a withered seed to
// revive. Latched: merely stopping does not heal the tree.
#define AI_TREE_REVIVE_SCORE    150

#define AI_METER_COLOR_ECO_MAX        0x2aff00
#define AI_METER_COLOR_AGGRESSIVE_MAX 0xff0000

#define AI_TAB_COLOR_ECO_MAX        0x39B73E
#define AI_TAB_COLOR_AGGRESSIVE_MAX 0xCB3328

// MinMaxScaler parameters — see ai_model/*_quantizer.json and feature_params.h
// Feature order (identical in both notebooks / quantizer JSONs):
//   [0]  speed_mean       [1]  speed_std        [2]  speed_p95
//   [3]  rpm_mean         [4]  rpm_std           [5]  rpm_p95
//   [6]  throttle_mean    [7]  throttle_std      [8]  throttle_p95
//   [9]  throttle_dp95    [10] brake_mean        [11] brake_p95
//   [12] brake_dp95       [13] a_mean            [14] a_std
//   [15] a_p95            [16] a_p05             [17] abs_a_mean
//   [18] jerk_abs_mean    [19] jerk_abs_p95

// Ring buffers: indices [0]=speed(km/h) [1]=rpm [2]=throttle [3]=brake [4]=accel(m/s²)
static float s_buf[5][WIN_SIZE];
static int   s_buf_head  = 0;
static int   s_buf_count = 0;

static uint32_t s_last_ts    = 0;
static float    s_last_spd_ms = 0.0f;

static volatile int32_t           s_score = AI_SCORE_START;
static volatile ai_driving_style_t s_style = AI_DRIVING_STYLE_NORMAL;
static volatile bool              s_ready  = false;

static bool       s_meter_color_init = false;
static lv_color_t s_meter_neutral_color;
static bool       s_tab_color_init = false;
static lv_color_t s_tab_neutral_color;

// Eco-tree UI state
static lv_obj_t *s_tree_img    = NULL;
static int       s_tree_stage  = -1;            // currently shown stage (-1 = not set)
static volatile uint32_t s_aggr_streak = 0;     // consecutive AGGRESSIVE windows
static volatile bool     s_withered    = false; // latched until score recovers

// Temp arrays (static to stay off the task stack)
static float s_ord[5][WIN_SIZE];       // ring buffer in temporal order
static float s_srt[5][WIN_SIZE];       // sorted versions
static float s_diff[3][DIFF_SIZE];     // [0]=|thr_diff| [1]=|brk_diff| [2]=|jerk|
static float s_srt_diff[3][DIFF_SIZE]; // sorted versions of s_diff

static int float_cmp(const void *a, const void *b)
{
    float fa = *(const float *)a;
    float fb = *(const float *)b;
    return (fa > fb) - (fa < fb);
}

// Linear interpolation percentile matching numpy default (method='linear')
static float percentile_sorted(const float *sorted, int n, float p)
{
    float idx = p * (float)(n - 1);
    int lo = (int)idx;
    int hi = lo + 1;
    if (hi >= n) return sorted[n - 1];
    return sorted[lo] + (idx - (float)lo) * (sorted[hi] - sorted[lo]);
}

static float arr_mean(const float *arr, int n)
{
    float s = 0.0f;
    for (int i = 0; i < n; i++) s += arr[i];
    return s / (float)n;
}

// Population std (ddof=0), matching numpy default
static float arr_std(const float *arr, int n, float m)
{
    float v = 0.0f;
    for (int i = 0; i < n; i++) {
        float d = arr[i] - m;
        v += d * d;
    }
    return sqrtf(v / (float)n);
}

static int16_t clamp_i16(float v)
{
    if (v > (float)INT16_MAX) return INT16_MAX;
    if (v < (float)INT16_MIN) return INT16_MIN;
    return (int16_t)lrintf(v);
}

static void reset_window(void)
{
    memset(s_buf,   0, sizeof(s_buf));
    s_buf_head   = 0;
    s_buf_count  = 0;
    s_last_ts    = 0;
    s_last_spd_ms = 0.0f;
}

void ai_model_init(void)
{
    reset_window();
    s_score = AI_SCORE_START;
    s_style = AI_DRIVING_STYLE_NORMAL;
    s_ready = false;
    s_aggr_streak = 0;
    s_withered = false;
}

void ai_model_process_sample(const can_data_t *data)
{
    if (data == NULL) return;

    // Mirror training-data filters: ignition on, not in reverse, not stopped (speed_mean >= 2 km/h)
    if (!data->ignition || data->rear_gear || data->speed < 2) {
        reset_window();
        s_style = AI_DRIVING_STYLE_NORMAL;
        s_ready = false;
        s_aggr_streak = 0;  // standing still is not aggression; s_withered stays latched
        return;
    }

    float dt_s = 0.1f;
    if (s_last_ts > 0 && data->timestamp > s_last_ts) {
        dt_s = (float)(data->timestamp - s_last_ts) / 1000.0f;
        if (dt_s < 0.01f) dt_s = 0.01f;
    }
    s_last_ts = data->timestamp;

    float spd_ms = (float)data->speed / 3.6f;
    float accel  = (spd_ms - s_last_spd_ms) / dt_s;
    s_last_spd_ms = spd_ms;

    s_buf[0][s_buf_head] = (float)data->speed;
    s_buf[1][s_buf_head] = (float)data->rpm;
    s_buf[2][s_buf_head] = (float)data->throttle_pedal;
    s_buf[3][s_buf_head] = (float)data->brake_pedal;
    s_buf[4][s_buf_head] = accel;
    s_buf_head = (s_buf_head + 1) % WIN_SIZE;
    if (s_buf_count < WIN_SIZE) s_buf_count++;

    if (s_buf_count < WIN_SIZE) {
        s_ready = false;
        return;
    }

    // Unroll ring buffer into temporal order (oldest → newest)
    for (int b = 0; b < 5; b++) {
        for (int i = 0; i < WIN_SIZE; i++) {
            s_ord[b][i] = s_buf[b][(s_buf_head + i) % WIN_SIZE];
        }
        memcpy(s_srt[b], s_ord[b], WIN_SIZE * sizeof(float));
        qsort(s_srt[b], WIN_SIZE, sizeof(float), float_cmp);
    }

    // Per-second derivatives (divide by DT, matching notebook d_*_s = diff / DT):
    //  [0] d_throttle_s (signed), [1] d_brake_s (signed), [2] |jerk_ms3| (abs)
    // throttle/brake keep their sign — *_dp95 takes the upper tail (sharp presses),
    // so signed vs abs matters when releases are sharper than presses.
    const float inv_dt = 1.0f / DT_S;
    for (int i = 0; i < DIFF_SIZE; i++) {
        s_diff[0][i] = (s_ord[2][i + 1] - s_ord[2][i]) * inv_dt;
        s_diff[1][i] = (s_ord[3][i + 1] - s_ord[3][i]) * inv_dt;
        s_diff[2][i] = fabsf(s_ord[4][i + 1] - s_ord[4][i]) * inv_dt;
    }
    for (int d = 0; d < 3; d++) {
        memcpy(s_srt_diff[d], s_diff[d], DIFF_SIZE * sizeof(float));
        qsort(s_srt_diff[d], DIFF_SIZE, sizeof(float), float_cmp);
    }

    float spd_mean = arr_mean(s_ord[0], WIN_SIZE);
    float rpm_mean = arr_mean(s_ord[1], WIN_SIZE);
    float thr_mean = arr_mean(s_ord[2], WIN_SIZE);
    float brk_mean = arr_mean(s_ord[3], WIN_SIZE);
    float a_mean   = arr_mean(s_ord[4], WIN_SIZE);

    float abs_a_mean = 0.0f;
    for (int i = 0; i < WIN_SIZE; i++) abs_a_mean += fabsf(s_ord[4][i]);
    abs_a_mean /= (float)WIN_SIZE;

    float raw[FEAT_COUNT];
    raw[0]  = spd_mean;
    raw[1]  = arr_std(s_ord[0], WIN_SIZE, spd_mean);
    raw[2]  = percentile_sorted(s_srt[0], WIN_SIZE, 0.95f);
    raw[3]  = rpm_mean;
    raw[4]  = arr_std(s_ord[1], WIN_SIZE, rpm_mean);
    raw[5]  = percentile_sorted(s_srt[1], WIN_SIZE, 0.95f);
    raw[6]  = thr_mean;
    raw[7]  = arr_std(s_ord[2], WIN_SIZE, thr_mean);
    raw[8]  = percentile_sorted(s_srt[2], WIN_SIZE, 0.95f);
    raw[9]  = percentile_sorted(s_srt_diff[0], DIFF_SIZE, 0.95f);
    raw[10] = brk_mean;
    raw[11] = percentile_sorted(s_srt[3], WIN_SIZE, 0.95f);
    raw[12] = percentile_sorted(s_srt_diff[1], DIFF_SIZE, 0.95f);
    raw[13] = a_mean;
    raw[14] = arr_std(s_ord[4], WIN_SIZE, a_mean);
    raw[15] = percentile_sorted(s_srt[4], WIN_SIZE, 0.95f);
    raw[16] = percentile_sorted(s_srt[4], WIN_SIZE, 0.05f);
    raw[17] = abs_a_mean;
    raw[18] = arr_mean(s_diff[2], DIFF_SIZE);
    raw[19] = percentile_sorted(s_srt_diff[2], DIFF_SIZE, 0.95f);

    int16_t features[FEAT_COUNT];
    for (int i = 0; i < FEAT_COUNT; i++) {
        features[i] = clamp_i16(raw[i] * AI_FEAT_SCALE[i] + AI_FEAT_MIN[i]);
    }

    int pred = (int)AI_MODEL_PREDICT(features, FEAT_COUNT);
    if (pred < 0 || pred > 2) return;

    s_style = (ai_driving_style_t)pred;
    s_ready = true;

    if (s_style == AI_DRIVING_STYLE_ECO && s_score < AI_SCORE_MAX) {
        s_score += AI_SCORE_ECO_STEP;
    } else if (s_style == AI_DRIVING_STYLE_AGGRESSIVE && s_score > AI_SCORE_MIN) {
        s_score -= AI_SCORE_AGGRESSIVE_STEP;
    }
    if (s_score < AI_SCORE_MIN) s_score = AI_SCORE_MIN;
    if (s_score > AI_SCORE_MAX) s_score = AI_SCORE_MAX;

    // Track sustained aggression for the eco-tree wither state (with hysteresis):
    // wither after a run of aggressive windows; revive only once eco driving
    // pulls the score back up.
    if (s_style == AI_DRIVING_STYLE_AGGRESSIVE) {
        if (s_aggr_streak < UINT32_MAX) s_aggr_streak++;
    } else {
        s_aggr_streak = 0;
    }
    if (s_aggr_streak >= AI_TREE_WITHER_WINDOWS) {
        s_withered = true;
    } else if (s_withered && s_score >= AI_TREE_REVIVE_SCORE) {
        s_withered = false;
    }
}

void ai_model_get_snapshot(ai_model_snapshot_t *out_snapshot)
{
    if (out_snapshot == NULL) return;
    out_snapshot->score = s_score;
    out_snapshot->style = s_style;
    out_snapshot->ready = s_ready;
}

// Map driver state to an eco-tree stage: 0 = withered, 1..6 = growth bands of score.
static int ai_tree_stage_from_state(int32_t score, bool withered)
{
    if (withered) return 0;
    int band = (int)((score - AI_SCORE_MIN) * AI_TREE_GROWTH_STAGES
                     / (AI_SCORE_MAX - AI_SCORE_MIN + 1));  // 0..5
    if (band < 0) band = 0;
    if (band > AI_TREE_GROWTH_STAGES - 1) band = AI_TREE_GROWTH_STAGES - 1;
    return band + 1;  // 1..6
}

// Create the tree image once, in place of the legacy score meter.
static void ai_tree_ensure_created(void)
{
    if (s_tree_img != NULL || objects.container_can_1 == NULL) return;

    if (objects.meter_score != NULL) {
        lv_obj_add_flag(objects.meter_score, LV_OBJ_FLAG_HIDDEN);
    }

    s_tree_img = lv_img_create(objects.container_can_1);
    lv_obj_add_flag(s_tree_img, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_clear_flag(s_tree_img, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_align(s_tree_img, LV_ALIGN_CENTER, 0, 0);
}

static void ai_tree_update(int32_t score, bool withered)
{
    ai_tree_ensure_created();
    if (s_tree_img == NULL) return;

    int stage = ai_tree_stage_from_state(score, withered);
    if (stage != s_tree_stage) {
        s_tree_stage = stage;
        lv_img_set_src(s_tree_img, eco_tree_stages[stage]);
    }
}

void ai_model_update_ui_locked(void)
{
    ai_model_snapshot_t snap;
    ai_model_get_snapshot(&snap);

    // Eco-tree grows/withers with the driving style (runs even if the legacy meter is absent).
    ai_tree_update(snap.score, s_withered);

    if (objects.meter_score == NULL || screen_screen_main_state.indicator == NULL) return;

    lv_meter_set_indicator_value(
        objects.meter_score,
        screen_screen_main_state.indicator,
        snap.score * 100 / AI_SCORE_MAX
    );

    if (!s_meter_color_init) {
        s_meter_neutral_color = lv_obj_get_style_bg_color(
            objects.meter_score, LV_PART_MAIN | LV_STATE_DEFAULT
        );
        s_meter_color_init = true;
    }

    int32_t score = snap.score;
    if (score < AI_SCORE_MIN) score = AI_SCORE_MIN;
    if (score > AI_SCORE_MAX) score = AI_SCORE_MAX;

    lv_color_t target = s_meter_neutral_color;
    uint8_t mix = 0;

    if (score < AI_SCORE_START) {
        target = lv_color_hex(AI_METER_COLOR_AGGRESSIVE_MAX);
        mix = (uint8_t)(((AI_SCORE_START - score) * 255) / AI_SCORE_START);
    } else if (score > AI_SCORE_START) {
        target = lv_color_hex(AI_METER_COLOR_ECO_MAX);
        mix = (uint8_t)(((score - AI_SCORE_START) * 255) / (AI_SCORE_MAX - AI_SCORE_START));
    }

    lv_obj_set_style_bg_color(
        objects.meter_score,
        lv_color_mix(target, s_meter_neutral_color, mix),
        LV_PART_MAIN | LV_STATE_DEFAULT
    );

    if (objects.container_can_1 != NULL) {
        if (!s_tab_color_init) {
            s_tab_neutral_color = lv_obj_get_style_bg_color(
                objects.container_can_1, LV_PART_MAIN | LV_STATE_DEFAULT
            );
            s_tab_color_init = true;
        }

        lv_color_t tab_color;
        if (!snap.ready || snap.style == AI_DRIVING_STYLE_NORMAL) {
            tab_color = s_tab_neutral_color;
        } else if (snap.style == AI_DRIVING_STYLE_AGGRESSIVE) {
            tab_color = lv_color_hex(AI_TAB_COLOR_AGGRESSIVE_MAX);
        } else {
            tab_color = lv_color_hex(AI_TAB_COLOR_ECO_MAX);
        }
        lv_obj_set_style_bg_color(
            objects.container_can_1,
            tab_color,
            LV_PART_MAIN | LV_STATE_DEFAULT
        );

        if (objects.container_can != NULL) {
            lv_obj_set_style_bg_color(
                objects.container_can,
                tab_color,
                LV_PART_MAIN | LV_STATE_DEFAULT
            );
        }
    }
}
