#include "ai_model.h"
#include "feature_params.h"  // ai_model/feature_params.h — auto-generated from the quantizer JSONs
#include "ui/screens.h"
#include "ui/eco_tree_images.h"  // generated by assets/tree/gen_assets.py

#include "esp_log.h"
#include "nvs.h"

#include <limits.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

// ---- Model selection -------------------------------------------------------
// Exactly one trained model is compiled in. Switch the active model by changing
// AI_MODEL_VARIANT (here or via a -D build flag). Only the selected model header
// is #included, so the unused model's tree arrays never reach the compiler.
//   AI_MODEL_VARIANT_RANDOM_FOREST -> ai_model/driving_style_model.h (current)
//   AI_MODEL_VARIANT_EXTRA_TREES   -> ai_model/eco_model.h           (legacy)
// Both models share the same 20 features and feature order; only the trained
// tree and the MinMaxScaler params (feature_params.h) differ.
#define AI_MODEL_VARIANT_EXTRA_TREES    0
#define AI_MODEL_VARIANT_RANDOM_FOREST  1

#ifndef AI_MODEL_VARIANT
#define AI_MODEL_VARIANT  AI_MODEL_VARIANT_EXTRA_TREES
#endif

#if AI_MODEL_VARIANT == AI_MODEL_VARIANT_RANDOM_FOREST
    #include "driving_style_model.h"
    #define AI_MODEL_PREDICT  driving_style_model_predict
    #define AI_FEAT_SCALE     RANDOM_FOREST_FEAT_SCALE
    #define AI_FEAT_MIN       RANDOM_FOREST_FEAT_MIN
#elif AI_MODEL_VARIANT == AI_MODEL_VARIANT_EXTRA_TREES
    #include "eco_model.h"
    #define AI_MODEL_PREDICT  eco_model_predict
    #define AI_FEAT_SCALE     EXTRA_TREES_FEAT_SCALE
    #define AI_FEAT_MIN       EXTRA_TREES_FEAT_MIN
#else
    #error "Invalid AI_MODEL_VARIANT — pick AI_MODEL_VARIANT_EXTRA_TREES or AI_MODEL_VARIANT_RANDOM_FOREST"
#endif
// ---------------------------------------------------------------------------

// Window length must match WIN_N from the ML notebooks: 5s at 10Hz = 50 samples.
// The logger task feeds one sample every 100ms (see sd_card.c), matching the
// notebook's fixed 10Hz resample grid.
#define WIN_SIZE  50
#define DIFF_SIZE 49  // WIN_SIZE - 1

// Fixed sample period (s) used for per-second derivatives, matching the notebook
// constant DT = 0.1 (d_throttle_s, d_brake_s, jerk_ms3 are all divided by DT).
#define DT_S 0.1f

#define AI_SCORE_MIN   0
#define AI_SCORE_MAX   1000
#define AI_SCORE_START 500

// Demo switch: 1 = tree states evolve 2x faster (score steps doubled, wither
// threshold halved). For presentations only; set to 0 for normal pacing.
// Can also be overridden via a -D build flag.
#ifndef AI_DEMO_FAST_TREE
#define AI_DEMO_FAST_TREE 1
#endif

#if AI_DEMO_FAST_TREE
#define AI_TREE_SPEED_MULT 2
#else
#define AI_TREE_SPEED_MULT 1
#endif

// Loss aversion: the score drops faster than it climbs, so aggressive driving is
// "felt" more strongly than eco driving is rewarded. Tunable.
#define AI_SCORE_ECO_STEP         (2 * AI_TREE_SPEED_MULT)
#define AI_SCORE_AGGRESSIVE_STEP  (4 * AI_TREE_SPEED_MULT)

// Eco-tree gamification: score (and sustained aggression) -> growth stage.
//   stage 0      = withered seed (sustained aggressive driving)
//   stages 1..6  = seed -> seedling -> sapling -> mature -> flowering -> fruiting
#define AI_TREE_GROWTH_STAGES   6
// Consecutive AGGRESSIVE windows before the seed withers (10Hz feed -> ~10s
// at normal pacing, ~5s in demo mode).
#define AI_TREE_WITHER_WINDOWS  (100 / AI_TREE_SPEED_MULT)
// Score the driver must climb back to (via eco driving) for a withered seed to
// revive. Latched: merely stopping does not heal the tree.
#define AI_TREE_REVIVE_SCORE    150

// Orchard gamification: a tree that reaches AI_SCORE_MAX (fully fruiting) is
// harvested into the orchard and the score restarts from AI_SCORE_START.
// A wither event removes one tree from the orchard. The count is persisted
// in NVS, so the orchard reflects long-term driving history.
#define AI_ORCHARD_SLOTS         30          // max trees shown on the AI view
#define AI_ORCHARD_NVS_NAMESPACE "storage"   // shared app namespace (see can.c)
#define AI_ORCHARD_NVS_KEY       "orchard_cnt"

#define AI_TAB_COLOR_ECO_MAX        0x39B73E
#define AI_TAB_COLOR_AGGRESSIVE_MAX 0xCB3328

// MinMaxScaler parameters — see ai_model/*_quantizer.json and feature_params.h
// Feature order (identical in both notebooks / quantizer JSONs):
//   [0]  speed_mean       [1]  speed_std        [2]  speed_p95
//   [3]  rpm_mean         [4]  rpm_std           [5]  rpm_p95
//   [6]  throttle_mean    [7]  throttle_std      [8]  throttle_p95
//   [9]  throttle_dp95    [10] brake_mean        [11] brake_p95
//   [12] brake_dp95       [13] a_mean            [14] a_std
//   [15] a_p95            [16] a_p05             [17] abs_a_mean
//   [18] jerk_abs_mean    [19] jerk_abs_p95

// Ring buffers: indices [0]=speed(km/h) [1]=rpm [2]=throttle [3]=brake [4]=accel(m/s²)
static float s_buf[5][WIN_SIZE];
static int   s_buf_head  = 0;
static int   s_buf_count = 0;

static uint32_t s_last_ts    = 0;
static float    s_last_spd_ms = 0.0f;

static volatile int32_t           s_score = AI_SCORE_START;
static volatile ai_driving_style_t s_style = AI_DRIVING_STYLE_NORMAL;
static volatile bool              s_ready  = false;

static bool       s_tab_color_init = false;
static lv_color_t s_tab_neutral_color;

// Eco-tree UI state
static lv_obj_t *s_tree_img    = NULL;
static int       s_tree_stage  = -1;            // currently shown stage (-1 = not set)
static volatile uint32_t s_aggr_streak = 0;     // consecutive AGGRESSIVE windows
static volatile bool     s_withered    = false; // latched until score recovers

// Orchard state (count is written by the sampling task, read by the LVGL task)
static volatile uint32_t s_orchard_count = 0;
static lv_obj_t *s_orchard_imgs[AI_ORCHARD_SLOTS];
static uint32_t  s_orchard_shown = UINT32_MAX;  // last rendered count (forces first draw)

// Hand-scattered "planting" spots (top-left px inside the right half of the
// screen, ~400x480) in harvest order — irregular on purpose so the orchard
// grows without visible rows or columns.
typedef struct { int16_t x, y; } ai_orchard_spot_t;
static const ai_orchard_spot_t s_orchard_spots[AI_ORCHARD_SLOTS] = {
    {150, 176}, { 36,  96}, {242, 262}, { 88, 300}, {296,  66},
    {196,  30}, { 14, 218}, {318, 176}, {148,  62}, {224, 140},
    { 56,  10}, {166, 296}, {282, 330}, {  6, 342}, {104, 140},
    {324,   8}, {236, 348}, { 20, 160}, {260,  18}, { 94,  44},
    { 12,  48}, {300, 240}, {186, 224}, { 60, 244}, {130, 366},
    {334, 292}, { 60, 356}, {262, 102}, {112, 236}, {196, 370},
};

// Edge glow overlay: screen border highlighted in the current driving-style
// color. Faked soft blur: stacked borders, wider and fainter toward the center.
#define AI_GLOW_LAYERS 6
static lv_obj_t *s_glow_layers[AI_GLOW_LAYERS];
// 3 px steps within the same 18 px band; per-layer opacities are lower because
// all layers stack up at the very edge (peak stays ~75% combined).
static const lv_coord_t s_glow_width[AI_GLOW_LAYERS] = {18, 15, 12, 9, 6, 3};
static const lv_opa_t   s_glow_opa[AI_GLOW_LAYERS]   = {LV_OPA_10, LV_OPA_10, LV_OPA_20,
                                                        LV_OPA_20, LV_OPA_30, LV_OPA_30};

static const char *TAG = "ai_model";

// Temp arrays (static to stay off the task stack)
static float s_ord[5][WIN_SIZE];       // ring buffer in temporal order
static float s_srt[5][WIN_SIZE];       // sorted versions
static float s_diff[3][DIFF_SIZE];     // [0]=|thr_diff| [1]=|brk_diff| [2]=|jerk|
static float s_srt_diff[3][DIFF_SIZE]; // sorted versions of s_diff

static int float_cmp(const void *a, const void *b)
{
    float fa = *(const float *)a;
    float fb = *(const float *)b;
    return (fa > fb) - (fa < fb);
}

// Linear interpolation percentile matching numpy default (method='linear')
static float percentile_sorted(const float *sorted, int n, float p)
{
    float idx = p * (float)(n - 1);
    int lo = (int)idx;
    int hi = lo + 1;
    if (hi >= n) return sorted[n - 1];
    return sorted[lo] + (idx - (float)lo) * (sorted[hi] - sorted[lo]);
}

static float arr_mean(const float *arr, int n)
{
    float s = 0.0f;
    for (int i = 0; i < n; i++) s += arr[i];
    return s / (float)n;
}

// Population std (ddof=0), matching numpy default
static float arr_std(const float *arr, int n, float m)
{
    float v = 0.0f;
    for (int i = 0; i < n; i++) {
        float d = arr[i] - m;
        v += d * d;
    }
    return sqrtf(v / (float)n);
}

static int16_t clamp_i16(float v)
{
    if (v > (float)INT16_MAX) return INT16_MAX;
    if (v < (float)INT16_MIN) return INT16_MIN;
    return (int16_t)lrintf(v);
}

static void ai_orchard_nvs_load(void)
{
    nvs_handle_t handle;
    if (nvs_open(AI_ORCHARD_NVS_NAMESPACE, NVS_READONLY, &handle) != ESP_OK) return;
    uint32_t cnt = 0;
    if (nvs_get_u32(handle, AI_ORCHARD_NVS_KEY, &cnt) == ESP_OK) {
        s_orchard_count = cnt;
    }
    nvs_close(handle);
}

static void ai_orchard_nvs_save(void)
{
    nvs_handle_t handle;
    if (nvs_open(AI_ORCHARD_NVS_NAMESPACE, NVS_READWRITE, &handle) != ESP_OK) {
        ESP_LOGW(TAG, "Failed to open NVS for orchard save");
        return;
    }
    if (nvs_set_u32(handle, AI_ORCHARD_NVS_KEY, s_orchard_count) == ESP_OK) {
        nvs_commit(handle);
    }
    nvs_close(handle);
}

// Clears all harvested trees (Settings -> Reset orchard). The grid redraws on
// the next ai_orchard_update() tick via the s_orchard_shown comparison.
void ai_model_reset_orchard(void)
{
    s_orchard_count = 0;
    ai_orchard_nvs_save();
    ESP_LOGI(TAG, "Orchard reset by user");
}

static void reset_window(void)
{
    memset(s_buf,   0, sizeof(s_buf));
    s_buf_head   = 0;
    s_buf_count  = 0;
    s_last_ts    = 0;
    s_last_spd_ms = 0.0f;
}

void ai_model_init(void)
{
    reset_window();
    s_score = AI_SCORE_START;
    s_style = AI_DRIVING_STYLE_NORMAL;
    s_ready = false;
    s_aggr_streak = 0;
    s_withered = false;
    ai_orchard_nvs_load();
}

void ai_model_process_sample(const can_data_t *data)
{
    if (data == NULL) return;

    // Mirror training-data filters: ignition on, not in reverse, not stopped (speed_mean >= 2 km/h)
    if (!data->ignition || data->rear_gear || data->speed < 2) {
        reset_window();
        s_style = AI_DRIVING_STYLE_NORMAL;
        s_ready = false;
        s_aggr_streak = 0;  // standing still is not aggression; s_withered stays latched
        return;
    }

    float dt_s = 0.1f;
    if (s_last_ts > 0 && data->timestamp > s_last_ts) {
        dt_s = (float)(data->timestamp - s_last_ts) / 1000.0f;
        if (dt_s < 0.01f) dt_s = 0.01f;
    }
    s_last_ts = data->timestamp;

    float spd_ms = (float)data->speed / 3.6f;
    float accel  = (spd_ms - s_last_spd_ms) / dt_s;
    s_last_spd_ms = spd_ms;

    s_buf[0][s_buf_head] = (float)data->speed;
    s_buf[1][s_buf_head] = (float)data->rpm;
    s_buf[2][s_buf_head] = (float)data->throttle_pedal;
    s_buf[3][s_buf_head] = (float)data->brake_pedal;
    s_buf[4][s_buf_head] = accel;
    s_buf_head = (s_buf_head + 1) % WIN_SIZE;
    if (s_buf_count < WIN_SIZE) s_buf_count++;

    if (s_buf_count < WIN_SIZE) {
        s_ready = false;
        return;
    }

    // Unroll ring buffer into temporal order (oldest → newest)
    for (int b = 0; b < 5; b++) {
        for (int i = 0; i < WIN_SIZE; i++) {
            s_ord[b][i] = s_buf[b][(s_buf_head + i) % WIN_SIZE];
        }
        memcpy(s_srt[b], s_ord[b], WIN_SIZE * sizeof(float));
        qsort(s_srt[b], WIN_SIZE, sizeof(float), float_cmp);
    }

    // Per-second derivatives (divide by DT, matching notebook d_*_s = diff / DT):
    //  [0] d_throttle_s (signed), [1] d_brake_s (signed), [2] |jerk_ms3| (abs)
    // throttle/brake keep their sign — *_dp95 takes the upper tail (sharp presses),
    // so signed vs abs matters when releases are sharper than presses.
    const float inv_dt = 1.0f / DT_S;
    for (int i = 0; i < DIFF_SIZE; i++) {
        s_diff[0][i] = (s_ord[2][i + 1] - s_ord[2][i]) * inv_dt;
        s_diff[1][i] = (s_ord[3][i + 1] - s_ord[3][i]) * inv_dt;
        s_diff[2][i] = fabsf(s_ord[4][i + 1] - s_ord[4][i]) * inv_dt;
    }
    for (int d = 0; d < 3; d++) {
        memcpy(s_srt_diff[d], s_diff[d], DIFF_SIZE * sizeof(float));
        qsort(s_srt_diff[d], DIFF_SIZE, sizeof(float), float_cmp);
    }

    float spd_mean = arr_mean(s_ord[0], WIN_SIZE);
    float rpm_mean = arr_mean(s_ord[1], WIN_SIZE);
    float thr_mean = arr_mean(s_ord[2], WIN_SIZE);
    float brk_mean = arr_mean(s_ord[3], WIN_SIZE);
    float a_mean   = arr_mean(s_ord[4], WIN_SIZE);

    float abs_a_mean = 0.0f;
    for (int i = 0; i < WIN_SIZE; i++) abs_a_mean += fabsf(s_ord[4][i]);
    abs_a_mean /= (float)WIN_SIZE;

    float raw[FEAT_COUNT];
    raw[0]  = spd_mean;
    raw[1]  = arr_std(s_ord[0], WIN_SIZE, spd_mean);
    raw[2]  = percentile_sorted(s_srt[0], WIN_SIZE, 0.95f);
    raw[3]  = rpm_mean;
    raw[4]  = arr_std(s_ord[1], WIN_SIZE, rpm_mean);
    raw[5]  = percentile_sorted(s_srt[1], WIN_SIZE, 0.95f);
    raw[6]  = thr_mean;
    raw[7]  = arr_std(s_ord[2], WIN_SIZE, thr_mean);
    raw[8]  = percentile_sorted(s_srt[2], WIN_SIZE, 0.95f);
    raw[9]  = percentile_sorted(s_srt_diff[0], DIFF_SIZE, 0.95f);
    raw[10] = brk_mean;
    raw[11] = percentile_sorted(s_srt[3], WIN_SIZE, 0.95f);
    raw[12] = percentile_sorted(s_srt_diff[1], DIFF_SIZE, 0.95f);
    raw[13] = a_mean;
    raw[14] = arr_std(s_ord[4], WIN_SIZE, a_mean);
    raw[15] = percentile_sorted(s_srt[4], WIN_SIZE, 0.95f);
    raw[16] = percentile_sorted(s_srt[4], WIN_SIZE, 0.05f);
    raw[17] = abs_a_mean;
    raw[18] = arr_mean(s_diff[2], DIFF_SIZE);
    raw[19] = percentile_sorted(s_srt_diff[2], DIFF_SIZE, 0.95f);

    int16_t features[FEAT_COUNT];
    for (int i = 0; i < FEAT_COUNT; i++) {
        features[i] = clamp_i16(raw[i] * AI_FEAT_SCALE[i] + AI_FEAT_MIN[i]);
    }

    int pred = (int)AI_MODEL_PREDICT(features, FEAT_COUNT);
    if (pred < 0 || pred > 2) return;

    s_style = (ai_driving_style_t)pred;
    s_ready = true;

    if (s_style == AI_DRIVING_STYLE_ECO && s_score < AI_SCORE_MAX) {
        s_score += AI_SCORE_ECO_STEP;
    } else if (s_style == AI_DRIVING_STYLE_AGGRESSIVE && s_score > AI_SCORE_MIN) {
        s_score -= AI_SCORE_AGGRESSIVE_STEP;
    }
    if (s_score < AI_SCORE_MIN) s_score = AI_SCORE_MIN;
    if (s_score > AI_SCORE_MAX) s_score = AI_SCORE_MAX;

    // Harvest: a fully fruiting tree (score at MAX) moves to the orchard and a
    // new tree starts from the neutral score.
    if (s_score >= AI_SCORE_MAX) {
        s_orchard_count++;
        ai_orchard_nvs_save();
        s_score = AI_SCORE_START;
        ESP_LOGI(TAG, "Tree harvested, orchard count: %lu", (unsigned long)s_orchard_count);
    }

    // Track sustained aggression for the eco-tree wither state (with hysteresis):
    // wither after a run of aggressive windows; revive only once eco driving
    // pulls the score back up.
    if (s_style == AI_DRIVING_STYLE_AGGRESSIVE) {
        if (s_aggr_streak < UINT32_MAX) s_aggr_streak++;
    } else {
        s_aggr_streak = 0;
    }
    if (s_aggr_streak >= AI_TREE_WITHER_WINDOWS) {
        // Wither transition costs one orchard tree (once per wither event —
        // s_withered stays latched until the score recovers).
        if (!s_withered) {
            s_withered = true;
            if (s_orchard_count > 0) {
                s_orchard_count--;
                ai_orchard_nvs_save();
                ESP_LOGI(TAG, "Tree withered, orchard count: %lu", (unsigned long)s_orchard_count);
            }
        }
    } else if (s_withered && s_score >= AI_TREE_REVIVE_SCORE) {
        s_withered = false;
    }
}

void ai_model_get_snapshot(ai_model_snapshot_t *out_snapshot)
{
    if (out_snapshot == NULL) return;
    out_snapshot->score = s_score;
    out_snapshot->style = s_style;
    out_snapshot->ready = s_ready;
}

// Map driver state to an eco-tree stage: 0 = withered, 1..6 = growth bands of score.
static int ai_tree_stage_from_state(int32_t score, bool withered)
{
    if (withered) return 0;
    int band = (int)((score - AI_SCORE_MIN) * AI_TREE_GROWTH_STAGES
                     / (AI_SCORE_MAX - AI_SCORE_MIN + 1));  // 0..5
    if (band < 0) band = 0;
    if (band > AI_TREE_GROWTH_STAGES - 1) band = AI_TREE_GROWTH_STAGES - 1;
    return band + 1;  // 1..6
}

// Create the split AI view once:
// left half = currently growing tree, right half = orchard of harvested trees.
static void ai_tree_ensure_created(void)
{
    if (s_tree_img != NULL || objects.container_can_1 == NULL) return;

    lv_obj_t *parent = objects.container_can_1;

    // Drop the generated pad_top so children span the full screen height.
    lv_obj_set_style_pad_top(parent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Full-screen meadow background: pale grass with a halo behind the growing
    // tree on the left, blending into a denser meadow under the orchard.
    lv_obj_set_style_bg_img_src(parent, &eco_meadow_bg, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Left half: the currently growing tree (live driving status).
    lv_obj_t *left = lv_obj_create(parent);
    lv_obj_remove_style_all(left);
    lv_obj_add_flag(left, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_clear_flag(left, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_size(left, LV_PCT(50), LV_PCT(100));
    lv_obj_align(left, LV_ALIGN_LEFT_MID, 0, 0);

    s_tree_img = lv_img_create(left);
    lv_obj_clear_flag(s_tree_img, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_align(s_tree_img, LV_ALIGN_CENTER, 0, 0);

    // Right half: the orchard (long-term driving history). Trees sit at fixed
    // scattered spots directly on the meadow background — no grid.
    lv_obj_t *right = lv_obj_create(parent);
    lv_obj_remove_style_all(right);
    lv_obj_add_flag(right, LV_OBJ_FLAG_IGNORE_LAYOUT);
    lv_obj_clear_flag(right, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_size(right, LV_PCT(50), LV_PCT(100));
    lv_obj_align(right, LV_ALIGN_RIGHT_MID, 0, 0);

    // Painter's order: create back-to-front (ascending y) so a tree lower on
    // the screen overlaps the ones behind it, regardless of harvest order.
    uint32_t order[AI_ORCHARD_SLOTS];
    for (uint32_t i = 0; i < AI_ORCHARD_SLOTS; i++) order[i] = i;
    for (uint32_t i = 1; i < AI_ORCHARD_SLOTS; i++) {
        uint32_t key = order[i];
        uint32_t j = i;
        while (j > 0 && s_orchard_spots[order[j - 1]].y > s_orchard_spots[key].y) {
            order[j] = order[j - 1];
            j--;
        }
        order[j] = key;
    }

    for (uint32_t k = 0; k < AI_ORCHARD_SLOTS; k++) {
        uint32_t slot = order[k];
        lv_obj_t *img = lv_img_create(right);
        lv_obj_clear_flag(img, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
        // Pre-scaled asset — no runtime zoom (LV_IMG_SIZE_MODE_REAL
        // rendering proved unreliable on this LVGL version).
        lv_img_set_src(img, &eco_tree_orchard);
        lv_obj_set_pos(img, s_orchard_spots[slot].x, s_orchard_spots[slot].y);
        lv_obj_add_flag(img, LV_OBJ_FLAG_HIDDEN);
        s_orchard_imgs[slot] = img;
    }

    // Edge glow: stacked transparent full-screen overlays, only their borders
    // are drawn. Widths/opacities approximate a blurred glow along the screen
    // perimeter. Parented to the tab page (zero padding), not container_can_1
    // (pad_top 12), so the glow hugs all four screen edges. Created last so
    // they sit on top.
    lv_obj_t *glow_parent = (objects.tab_ai != NULL) ? objects.tab_ai : parent;
    for (int i = 0; i < AI_GLOW_LAYERS; i++) {
        lv_obj_t *obj = lv_obj_create(glow_parent);
        lv_obj_remove_style_all(obj);
        lv_obj_add_flag(obj, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(obj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_size(obj, LV_PCT(100), LV_PCT(100));
        lv_obj_align(obj, LV_ALIGN_CENTER, 0, 0);
        lv_obj_set_style_border_width(obj, s_glow_width[i], LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_opa(obj, s_glow_opa[i], LV_PART_MAIN | LV_STATE_DEFAULT);
        s_glow_layers[i] = obj;
    }
}

// Show the screen-edge glow in the driving-style color (hidden for NORMAL).
static void ai_glow_update(const ai_model_snapshot_t *snap)
{
    if (s_glow_layers[0] == NULL) return;

    bool visible = snap->ready && snap->style != AI_DRIVING_STYLE_NORMAL;
    lv_color_t color = lv_color_hex(snap->style == AI_DRIVING_STYLE_AGGRESSIVE
                                        ? AI_TAB_COLOR_AGGRESSIVE_MAX
                                        : AI_TAB_COLOR_ECO_MAX);

    for (int i = 0; i < AI_GLOW_LAYERS; i++) {
        if (visible) {
            lv_obj_set_style_border_color(s_glow_layers[i], color, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_clear_flag(s_glow_layers[i], LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_add_flag(s_glow_layers[i], LV_OBJ_FLAG_HIDDEN);
        }
    }
}

// Sync the orchard grid with the current count.
static void ai_orchard_update(void)
{
    if (s_orchard_imgs[0] == NULL) return;

    uint32_t cnt = s_orchard_count;
    if (cnt == s_orchard_shown) return;
    s_orchard_shown = cnt;
    ESP_LOGI(TAG, "Orchard render: %lu trees", (unsigned long)cnt);

    uint32_t shown = cnt < AI_ORCHARD_SLOTS ? cnt : AI_ORCHARD_SLOTS;
    for (uint32_t i = 0; i < AI_ORCHARD_SLOTS; i++) {
        if (i < shown) {
            lv_obj_clear_flag(s_orchard_imgs[i], LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_add_flag(s_orchard_imgs[i], LV_OBJ_FLAG_HIDDEN);
        }
    }
}

static void ai_tree_update(int32_t score, bool withered)
{
    ai_tree_ensure_created();
    if (s_tree_img == NULL) return;

    int stage = ai_tree_stage_from_state(score, withered);
    if (stage != s_tree_stage) {
        s_tree_stage = stage;
        lv_img_set_src(s_tree_img, eco_tree_stages[stage]);
    }
}

void ai_model_update_ui_locked(void)
{
    ai_model_snapshot_t snap;
    ai_model_get_snapshot(&snap);

    // Eco-tree grows/withers with the driving style.
    ai_tree_update(snap.score, s_withered);
    ai_orchard_update();
    ai_glow_update(&snap);

    // Tint the CAN page background with the current driving style (the AI page
    // is covered by the meadow image; its feedback is the tree + edge glow).
    if (objects.container_can != NULL) {
        if (!s_tab_color_init) {
            s_tab_neutral_color = lv_obj_get_style_bg_color(
                objects.container_can, LV_PART_MAIN | LV_STATE_DEFAULT
            );
            s_tab_color_init = true;
        }

        lv_color_t tab_color;
        if (!snap.ready || snap.style == AI_DRIVING_STYLE_NORMAL) {
            tab_color = s_tab_neutral_color;
        } else if (snap.style == AI_DRIVING_STYLE_AGGRESSIVE) {
            tab_color = lv_color_hex(AI_TAB_COLOR_AGGRESSIVE_MAX);
        } else {
            tab_color = lv_color_hex(AI_TAB_COLOR_ECO_MAX);
        }
        lv_obj_set_style_bg_color(
            objects.container_can,
            tab_color,
            LV_PART_MAIN | LV_STATE_DEFAULT
        );
    }
}
