#!/usr/bin/env python3
# Reads the quantizer JSON of every trained model and generates feature_params.h
# with per-model MinMaxScaler arrays. ai_model.c selects one set via AI_MODEL_VARIANT.
# Run manually or via CMakeLists.txt at configure time.
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_PATH   = os.path.join(SCRIPT_DIR, "feature_params.h")

# (C array prefix, quantizer json filename) — keep prefixes in sync with ai_model.c.
# Prefix = training algorithm: ExtraTrees (legacy) vs RandomForest (current).
MODELS = [
    ("EXTRA_TREES",   "feature_quantizer.json"),
    ("RANDOM_FOREST", "driving_style_quantizer.json"),
]


def load_quantizer(filename):
    with open(os.path.join(SCRIPT_DIR, filename)) as f:
        data = json.load(f)
    scale = data["scale"]
    mins  = data["min"]
    assert len(scale) == len(mins), f"scale/min length mismatch in {filename}"
    return scale, mins, data["feature_order"]


def fmt_rows(values, name):
    lines = [f"static const float {name}[FEAT_COUNT] = {{"]
    rows_per_line = 5
    for i in range(0, len(values), rows_per_line):
        chunk = values[i:i + rows_per_line]
        last  = i + rows_per_line >= len(values)
        row   = "    " + ", ".join(f"{v:.10f}f" for v in chunk)
        lines.append(row if last else row + ",")
    lines.append("};")
    return lines


loaded = [(prefix, *load_quantizer(fname)) for prefix, fname in MODELS]

# All models must share the same feature count and ordering.
ref_order = loaded[0][3]
for prefix, scale, mins, order in loaded:
    assert order == ref_order, f"feature_order of {prefix} differs from reference"
n = len(ref_order)

lines = [
    "// Auto-generated by gen_params.py from the per-model quantizer JSONs — do not edit manually",
    "#ifndef FEATURE_PARAMS_H",
    "#define FEATURE_PARAMS_H",
    "",
    f"#define FEAT_COUNT {n}",
    "",
]
for prefix, scale, mins, _order in loaded:
    lines += fmt_rows(scale, f"{prefix}_FEAT_SCALE")
    lines.append("")
    lines += fmt_rows(mins, f"{prefix}_FEAT_MIN")
    lines.append("")
lines += ["#endif // FEATURE_PARAMS_H", ""]

with open(OUT_PATH, "w", newline="\n") as f:
    f.write("\n".join(lines))

print(f"[gen_params] Generated {OUT_PATH} for: {', '.join(p for p, _ in MODELS)}")
