// Auto-generated by assets/tree/gen_assets.py -- do not edit by hand.
#ifndef ECO_TREE_IMAGES_H
#define ECO_TREE_IMAGES_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ECO_TREE_STAGE_COUNT 7

extern const lv_img_dsc_t eco_tree_0_withered;
extern const lv_img_dsc_t eco_tree_1_seed;
extern const lv_img_dsc_t eco_tree_2_seedling;
extern const lv_img_dsc_t eco_tree_3_sapling;
extern const lv_img_dsc_t eco_tree_4_mature;
extern const lv_img_dsc_t eco_tree_5_flowering;
extern const lv_img_dsc_t eco_tree_6_fruiting;
extern const lv_img_dsc_t eco_meadow_bg;
extern const lv_img_dsc_t eco_tree_orchard;

// Stages ordered worst -> best (index 0 = withered, last = fruiting).
extern const lv_img_dsc_t *const eco_tree_stages[ECO_TREE_STAGE_COUNT];

#ifdef __cplusplus
}
#endif

#endif // ECO_TREE_IMAGES_H
